/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import java.awt.Image;
import java.io.File;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import model.employee;
import model.employeeHistory;

/**
 *
 * @author manognapalla
 */
public class createJPanel extends javax.swing.JPanel {

    /**
     * Creates new form createJPanel
     */
    employeeHistory history;
    
    public createJPanel(employeeHistory history) {
        initComponents();
        this.history = history;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Iblname = new javax.swing.JLabel();
        IblemployeeID = new javax.swing.JLabel();
        IblAge = new javax.swing.JLabel();
        Iblgender = new javax.swing.JLabel();
        Iblstartdate = new javax.swing.JLabel();
        Ibllevel = new javax.swing.JLabel();
        lblteaminfo = new javax.swing.JLabel();
        lblposition = new javax.swing.JLabel();
        lblcellphonenumber = new javax.swing.JLabel();
        lblemail = new javax.swing.JLabel();
        lblemployeedetails = new javax.swing.JLabel();
        txtname = new javax.swing.JTextField();
        txtemployeeid = new javax.swing.JTextField();
        txtage = new javax.swing.JTextField();
        txtgender = new javax.swing.JTextField();
        txtstartdate = new javax.swing.JTextField();
        txtlevel = new javax.swing.JTextField();
        txtteaminfo = new javax.swing.JTextField();
        txtpositiontitle = new javax.swing.JTextField();
        txtcellphonenumber = new javax.swing.JTextField();
        txtemail = new javax.swing.JTextField();
        btnsave = new javax.swing.JButton();
        lblContactinfo = new javax.swing.JLabel();
        lblnamevalidation = new javax.swing.JLabel();
        lblemployeeidvalidation = new javax.swing.JLabel();
        lblagevalidation = new javax.swing.JLabel();
        lblgendervalidation = new javax.swing.JLabel();
        lblstartdatevalidation = new javax.swing.JLabel();
        lbllevelvalidation = new javax.swing.JLabel();
        lblteaminfovalidation = new javax.swing.JLabel();
        lblpositiontitlevalidation = new javax.swing.JLabel();
        lblcellphonenumbervalidation = new javax.swing.JLabel();
        lblemailvalidation = new javax.swing.JLabel();
        Imageuploadhere = new javax.swing.JLabel();
        Browse = new javax.swing.JButton();
        lblimage = new javax.swing.JLabel();

        Iblname.setText("Name:");

        IblemployeeID.setText("EmployeeID:");

        IblAge.setText("Age:");

        Iblgender.setText("Gender:");

        Iblstartdate.setText("Start Date:");

        Ibllevel.setText("Level:");

        lblteaminfo.setText("Team Info:");

        lblposition.setText("PositionTitle:");

        lblcellphonenumber.setText("Cell Phone Number:");

        lblemail.setText("                    Email:");

        lblemployeedetails.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        lblemployeedetails.setText("                                                        Employee Details");
        lblemployeedetails.setSize(new java.awt.Dimension(42, 25));

        txtname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnameActionPerformed(evt);
            }
        });
        txtname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtnameKeyReleased(evt);
            }
        });

        txtage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtageActionPerformed(evt);
            }
        });

        txtstartdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtstartdateActionPerformed(evt);
            }
        });

        txtlevel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtlevelKeyReleased(evt);
            }
        });

        txtteaminfo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtteaminfoKeyReleased(evt);
            }
        });

        txtpositiontitle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpositiontitleActionPerformed(evt);
            }
        });
        txtpositiontitle.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtpositiontitleKeyReleased(evt);
            }
        });

        txtcellphonenumber.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtcellphonenumberKeyReleased(evt);
            }
        });

        txtemail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtemailActionPerformed(evt);
            }
        });
        txtemail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtemailKeyReleased(evt);
            }
        });

        btnsave.setText("Save");
        btnsave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsaveActionPerformed(evt);
            }
        });

        lblContactinfo.setText("Contact Information:");

        Imageuploadhere.setText("Image");

        Browse.setText("Browse to Add");
        Browse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BrowseActionPerformed(evt);
            }
        });

        lblimage.setForeground(new java.awt.Color(153, 153, 255));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblemployeedetails, javax.swing.GroupLayout.DEFAULT_SIZE, 935, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(259, 259, 259)
                        .addComponent(btnsave)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(lblContactinfo)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(lblemail, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtemail, javax.swing.GroupLayout.PREFERRED_SIZE, 427, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(lblcellphonenumber)
                        .addGap(18, 18, 18)
                        .addComponent(txtcellphonenumber, javax.swing.GroupLayout.PREFERRED_SIZE, 427, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(70, 268, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblcellphonenumbervalidation)
                    .addComponent(lblemailvalidation))
                .addGap(28, 28, 28))
            .addGroup(layout.createSequentialGroup()
                .addGap(116, 116, 116)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblposition)
                    .addComponent(lblteaminfo)
                    .addComponent(Ibllevel)
                    .addComponent(Iblstartdate)
                    .addComponent(Iblgender)
                    .addComponent(IblAge)
                    .addComponent(IblemployeeID)
                    .addComponent(Iblname))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(txtpositiontitle, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 427, Short.MAX_VALUE)
                    .addComponent(txtteaminfo, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtlevel, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtstartdate, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtgender, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtage, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtemployeeid, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtname, javax.swing.GroupLayout.Alignment.LEADING))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Browse)
                        .addGap(61, 61, 61))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lblemployeeidvalidation, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblgendervalidation, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblstartdatevalidation, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbllevelvalidation, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblteaminfovalidation, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblpositiontitlevalidation, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblagevalidation, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                            .addComponent(lblnamevalidation, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblimage, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Imageuploadhere)
                .addGap(105, 105, 105))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblemployeedetails, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtname)
                        .addComponent(lblnamevalidation))
                    .addComponent(Iblname, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(Imageuploadhere, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtemployeeid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(IblemployeeID)
                                    .addComponent(lblemployeeidvalidation))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(IblAge)
                                    .addComponent(lblagevalidation))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtgender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Iblgender)
                                    .addComponent(lblgendervalidation))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(txtstartdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(Iblstartdate))
                                    .addComponent(lblstartdatevalidation)))
                            .addComponent(lblimage, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Ibllevel)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtlevel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lbllevelvalidation))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(233, 233, 233)
                        .addComponent(Browse)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblteaminfo)
                    .addComponent(txtteaminfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblteaminfovalidation))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblposition)
                    .addComponent(txtpositiontitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblpositiontitlevalidation))
                .addGap(18, 18, 18)
                .addComponent(lblContactinfo, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtcellphonenumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblcellphonenumber)
                    .addComponent(lblcellphonenumbervalidation))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtemail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblemail)
                    .addComponent(lblemailvalidation))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnsave)
                .addContainerGap(222, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnameActionPerformed

    private void txtageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtageActionPerformed

    private void txtstartdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtstartdateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtstartdateActionPerformed

    private void txtpositiontitleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpositiontitleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpositiontitleActionPerformed

    private void btnsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsaveActionPerformed
        // TODO add your handling code here:
        
        String name = txtname.getText();
        int employeeID = Integer.parseInt(txtemployeeid.getText());
        int age = Integer.parseInt(txtage.getText());
        String gender = txtgender.getText();
        String startdate = txtstartdate.getText();
        String level = txtlevel.getText();
        String teaminfo = txtteaminfo.getText();
        String positiontitle = txtpositiontitle.getText();
        String cellphone = txtcellphonenumber.getText();
        String email = txtemail.getText();
        
        employee emp = history.addNewEmployee();
        
        emp.setName(name);
        emp.setEmployeeID(employeeID);
        emp.setAge(age);
        emp.setGender(gender);
        emp.setStartDate(startdate);
        emp.setLevel(level);
        emp.setTeaminfo(teaminfo);
        emp.setPositiontitle(positiontitle);
        emp.setCellPhone(cellphone);
        emp.setEmail(email);
        
        JOptionPane.showMessageDialog(this, "New Employee Added.");
        
        txtname.setText("");
        txtemployeeid.setText("");
        txtage.setText("");
        txtgender.setText("");
        txtstartdate.setText("");
        txtlevel.setText("");
        txtteaminfo.setText("");
        txtpositiontitle.setText("");
        txtcellphonenumber.setText("");
        txtemail.setText("");
   
    }//GEN-LAST:event_btnsaveActionPerformed

    private void txtnameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnameKeyReleased
        // TODO add your handling code here:
        String PATTERN ="^[a-zA-Z0-9]{0,30}$";
        Pattern name = Pattern.compile(PATTERN);
        Matcher match = name.matcher(txtname.getText());
         if(!match.matches()){
             lblnamevalidation.setText("Please Enter correct data!");
         }
         else{
             lblnamevalidation.setText(null);
         }
        
        
    }//GEN-LAST:event_txtnameKeyReleased

    private void txtlevelKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtlevelKeyReleased
        // TODO add your handling code here:
        String PATTERN ="^[a-zA-Z0-9]{1,30}$";
        Pattern name = Pattern.compile(PATTERN);
        Matcher match = name.matcher(txtlevel.getText());
         if(!match.matches()){
             lbllevelvalidation.setText("Please Enter correct data!");
         }
         else{
             lbllevelvalidation.setText(null);
         }
        
        
        
    }//GEN-LAST:event_txtlevelKeyReleased

    private void txtteaminfoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtteaminfoKeyReleased
        // TODO add your handling code here:
        
        String PATTERN ="^[a-zA-Z0-9]{1,30}$";
        Pattern name = Pattern.compile(PATTERN);
        Matcher match = name.matcher(txtteaminfo.getText());
         if(!match.matches()){
             lblteaminfovalidation.setText("Please Enter correct data!");
         }
         else{
             lblteaminfovalidation.setText(null);
         }
        
      
    }//GEN-LAST:event_txtteaminfoKeyReleased

    private void txtpositiontitleKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtpositiontitleKeyReleased
        // TODO add your handling code here:
        String PATTERN ="^[a-zA-Z0-9]{1,30}$";
        Pattern name = Pattern.compile(PATTERN);
        Matcher match = name.matcher(txtpositiontitle.getText());
         if(!match.matches()){
             lblpositiontitlevalidation.setText("Please Enter correct data!");
         }
         else{
             lblpositiontitlevalidation.setText(null);
         }
    }//GEN-LAST:event_txtpositiontitleKeyReleased

    private void txtcellphonenumberKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcellphonenumberKeyReleased
        // TODO add your handling code here:
        
        String PATTERN ="^[0-9]{0,12}$";
        Pattern name = Pattern.compile(PATTERN);
        Matcher match = name.matcher(txtcellphonenumber.getText());
         if(!match.matches()){
             lblcellphonenumbervalidation.setText("Please Enter correct data!");
         }
         else{
             lblcellphonenumbervalidation.setText(null);
         }
        
    }//GEN-LAST:event_txtcellphonenumberKeyReleased

    private void txtemailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtemailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtemailActionPerformed

    private void txtemailKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtemailKeyReleased
        // TODO add your handling code here:
        String PATTERN ="[a-zA-Z0-9]{0,30}[@][a-zA-Z0-9]{0,10}[.][a-zA-Z{0,5}]$";
        Pattern name = Pattern.compile(PATTERN);
        Matcher match = name.matcher(txtemail.getText());
         if(!match.matches()){
             lblemailvalidation.setText("Please Enter correct data!");
         }
         else{
             lblemailvalidation.setText(null);
         }
    }//GEN-LAST:event_txtemailKeyReleased

    String selectedImagePath;
    private void BrowseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BrowseActionPerformed
        // TODO add your handling code here:
        JFileChooser browseImageFile = new JFileChooser();
        
        FileNameExtensionFilter fnef = new FileNameExtensionFilter("IMAGES","png", "jpg" );
        browseImageFile.addChoosableFileFilter(fnef);
        int showOpenDialogue = browseImageFile.showOpenDialog(null);
        
        if(showOpenDialogue == JFileChooser.APPROVE_OPTION){
            File selectedImageFile = browseImageFile.getSelectedFile();
            selectedImagePath = selectedImageFile.getAbsolutePath();
            JOptionPane.showMessageDialog(null, selectedImagePath);
            ImageIcon ii = new ImageIcon(selectedImagePath);
            Image image = ii.getImage().getScaledInstance(lblimage.getWidth(),lblimage.getHeight(), WIDTH);
            lblimage.setIcon(new ImageIcon(image));
            
            
            
        }
        
    }//GEN-LAST:event_BrowseActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Browse;
    private javax.swing.JLabel IblAge;
    private javax.swing.JLabel IblemployeeID;
    private javax.swing.JLabel Iblgender;
    private javax.swing.JLabel Ibllevel;
    private javax.swing.JLabel Iblname;
    private javax.swing.JLabel Iblstartdate;
    private javax.swing.JLabel Imageuploadhere;
    private javax.swing.JButton btnsave;
    private javax.swing.JLabel lblContactinfo;
    private javax.swing.JLabel lblagevalidation;
    private javax.swing.JLabel lblcellphonenumber;
    private javax.swing.JLabel lblcellphonenumbervalidation;
    private javax.swing.JLabel lblemail;
    private javax.swing.JLabel lblemailvalidation;
    private javax.swing.JLabel lblemployeedetails;
    private javax.swing.JLabel lblemployeeidvalidation;
    private javax.swing.JLabel lblgendervalidation;
    private javax.swing.JLabel lblimage;
    private javax.swing.JLabel lbllevelvalidation;
    private javax.swing.JLabel lblnamevalidation;
    private javax.swing.JLabel lblposition;
    private javax.swing.JLabel lblpositiontitlevalidation;
    private javax.swing.JLabel lblstartdatevalidation;
    private javax.swing.JLabel lblteaminfo;
    private javax.swing.JLabel lblteaminfovalidation;
    private javax.swing.JTextField txtage;
    private javax.swing.JTextField txtcellphonenumber;
    private javax.swing.JTextField txtemail;
    private javax.swing.JTextField txtemployeeid;
    private javax.swing.JTextField txtgender;
    private javax.swing.JTextField txtlevel;
    private javax.swing.JTextField txtname;
    private javax.swing.JTextField txtpositiontitle;
    private javax.swing.JTextField txtstartdate;
    private javax.swing.JTextField txtteaminfo;
    // End of variables declaration//GEN-END:variables
}
